name = "fortran-zlib"
version = "0.1.0"
license = "ISC"
author = "Philipp Engel"
maintainer = "@interkosmos"
copyright = "Copyright (c) 2022, Philipp Engel"
description = "Fortran 2018 ISO_C_BINDING interfaces to zlib"
keywords = ["zlib"]

[build]
link = "z"

[library]
source-dir = "src"

[[test]]
name = "test_zlib"
source-dir = "test"
main = "test_zlib.f90"
